tasks:
  - init: |
      pip install -r dev-requirements.txt
      npm install && npm run build && python setup.py sdist
      pip install dist/dash_table-*.tar.gz
      pip install dash
    command:
      python example.py
